// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsHelix
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsHelix.a982d81c-8137-4121-97ec-2c99c012c26a";
        public const string Name = "VsHelix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
