// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VsHelix
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string VsHelixString = "d8c5a252-a96b-42ce-81c6-b57e22382eb6";
		public static Guid VsHelix = new Guid(VsHelixString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
	}
}